<a href="https://colab.research.google.com/github/vidyasreedharan2003-a11y/ML-PROJECT/blob/main/Day2_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset("titanic")

In [3]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.shape

(891, 15)

In [6]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [7]:
df.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [9]:
df.dtypes

,0
survived,int64
pclass,int64
sex,object
age,float64
sibsp,int64
parch,int64
fare,float64
embarked,object
class,category
who,object


In [10]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,177
sibsp,0
parch,0
fare,0
embarked,2
class,0
who,0


In [11]:
df.dropna()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True


In [12]:
df=df.drop(columns=['deck'])

In [13]:
df.shape

(891, 14)

In [14]:
df.dropna(subset=['embarked','embark_town'],inplace=True)  #To remove the null values inside the column

In [15]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64


In [16]:
age_mean=df['age'].mean()

In [17]:
df['age']=df['age'].fillna(age_mean)

In [18]:
df['age_group']=np.where(df['age']<18,"Child","Adult")

In [19]:
df['age_group']

,age_group
0,Adult
1,Adult
2,Adult
3,Adult
4,Adult
...,...
886,Adult
887,Adult
888,Adult
889,Adult


In [20]:
df['family_size']=df['sibsp']+df['parch']

In [21]:
df['family_size']

,family_size
0,1
1,1
2,0
3,1
4,0
...,...
886,0
887,0
888,3
889,0


In [22]:
df['fare_per_pearson']=df['fare']/(df['family_size']+1)

In [23]:
df['fare_per_pearson']

,fare_per_pearson
0,3.62500
1,35.64165
2,7.92500
3,26.55000
4,8.05000
...,...
886,13.00000
887,30.00000
888,5.86250
889,30.00000


In [24]:
df.rename(columns={'pclass':'passenger_class'},inplace=True)

In [25]:
df

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_pearson
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False,Adult,1,3.62500
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.64165
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,Adult,0,7.92500
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.55000
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True,Adult,0,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True,Adult,0,13.00000
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True,Adult,0,30.00000
888,0,3,female,29.642093,1,2,23.4500,S,Third,woman,False,Southampton,no,False,Adult,3,5.86250
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True,Adult,0,30.00000


In [26]:
df[df['age']>df['age'].mean()]   #To get age greater than its mean value

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_pearson
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.641650
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.550000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True,Adult,0,8.050000
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,Southampton,no,True,Adult,0,51.862500
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,Southampton,yes,True,Adult,0,26.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,Southampton,no,True,Adult,0,9.000000
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.579150
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,Southampton,no,True,Adult,0,7.895800
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,Queenstown,no,False,Adult,5,4.854167


In [27]:
df[(df['sex']=='female')&(df['passenger_class']==1)]  #to get female passengers with passenger class 1

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_pearson
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.641650
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.550000
11,1,1,female,58.000000,0,0,26.5500,S,First,woman,False,Southampton,yes,True,Adult,0,26.550000
31,1,1,female,29.642093,1,0,146.5208,C,First,woman,False,Cherbourg,yes,False,Adult,1,73.260400
52,1,1,female,49.000000,1,0,76.7292,C,First,woman,False,Cherbourg,yes,False,Adult,1,38.364600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.000000,1,1,164.8667,S,First,woman,False,Southampton,yes,False,Adult,2,54.955567
862,1,1,female,48.000000,0,0,25.9292,S,First,woman,False,Southampton,yes,True,Adult,0,25.929200
871,1,1,female,47.000000,1,1,52.5542,S,First,woman,False,Southampton,yes,False,Adult,2,17.518067
879,1,1,female,56.000000,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.579150


In [28]:
df[df['survived']==1]

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_pearson
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.64165
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,Adult,0,7.92500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.55000
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,Southampton,yes,False,Adult,2,3.71110
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,Cherbourg,yes,False,Child,1,15.03540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,Cherbourg,yes,True,Child,0,7.22500
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.57915
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,Southampton,yes,False,Adult,1,13.00000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True,Adult,0,30.00000


In [29]:
df.groupby('sex')['survived'].mean()   #survival rate by gender

,survived
sex,
female,0.740385
male,0.188908


In [30]:
df.groupby('passenger_class')['fare'].mean()   #average fare by class

,fare
passenger_class,
1,84.193516
2,20.662183
3,13.675550


In [31]:
df.corr(numeric_only=True)

,survived,passenger_class,age,sibsp,parch,fare,adult_male,alone,family_size,fare_per_pearson
survived,1.000000,-0.335549,-0.074513,-0.034040,0.083151,0.255290,-0.555520,-0.206207,0.018277,0.217902
passenger_class,-0.335549,1.000000,-0.328256,0.081656,0.016824,-0.548193,0.090098,0.138553,0.064221,-0.482024
age,-0.074513,-0.328256,1.000000,-0.231908,-0.178013,0.088780,0.258793,0.177445,-0.247459,0.136787
sibsp,-0.034040,0.081656,-0.231908,1.000000,0.414542,0.160887,-0.255401,-0.584186,0.890654,-0.093211
parch,0.083151,0.016824,-0.178013,0.414542,1.000000,0.217532,-0.351945,-0.583112,0.782988,-0.067422
fare,0.255290,-0.548193,0.088780,0.160887,0.217532,1.000000,-0.179851,-0.274079,0.218658,0.840902
adult_male,-0.555520,0.090098,0.258793,-0.255401,-0.351945,-0.179851,1.000000,0.407992,-0.350419,-0.078503
alone,-0.206207,0.138553,0.177445,-0.584186,-0.583112,-0.274079,0.407992,1.000000,-0.690654,0.042706
family_size,0.018277,0.064221,-0.247459,0.890654,0.782988,0.218658,-0.350419,-0.690654,1.000000,-0.097399
fare_per_pearson,0.217902,-0.482024,0.136787,-0.093211,-0.067422,0.840902,-0.078503,0.042706,-0.097399,1.000000


In [32]:
df2=sns.load_dataset("tips")

In [33]:
df2

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [35]:
df2.shape

(244, 7)

In [36]:
df2.size

1708

In [37]:
df2.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [38]:
df2.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


In [39]:
df2.dtypes

,0
total_bill,float64
tip,float64
sex,category
smoker,category
day,category
time,category
size,int64


In [40]:
df2.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [41]:
df2.isnull().sum()

,0
total_bill,0
tip,0
sex,0
smoker,0
day,0
time,0
size,0


In [42]:
df2['total_bill'].mean()

np.float64(19.78594262295082)

In [43]:
df2['tip'].mean()

np.float64(2.99827868852459)

In [44]:
df2['tip'].median()

2.9

In [58]:
df2['tip_percentage']=(df2['tip']/df2['total_bill'])*100

In [59]:
df2['tip_percentage']


,tip_percentage
0,5.944673
1,16.054159
2,16.658734
3,13.978041
4,14.680765
...,...
239,20.392697
240,7.358352
241,8.822232
242,9.820426


In [47]:
df2

,total_bill,tip,sex,smoker,day,time,size,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765
...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426


In [48]:
average_bill=df2['total_bill'].mean()

In [49]:
df2['high_spender']=np.where(df2['total_bill']>average_bill,1,0)

In [50]:
df2

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,high_spender
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,0
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,0
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,1
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,1
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,1
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,1
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352,1
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232,1
242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426,0


In [51]:
df2[df2['total_bill']>30]

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,high_spender
11,35.26,5.00,Female,No,Sun,Dinner,4,14.180374,1
23,39.42,7.58,Male,No,Sat,Dinner,4,19.228818,1
39,31.27,5.00,Male,No,Sat,Dinner,3,15.989767,1
44,30.40,5.60,Male,No,Sun,Dinner,4,18.421053,1
47,32.40,6.00,Male,No,Sun,Dinner,4,18.518519,1
52,34.81,5.20,Female,No,Sun,Dinner,4,14.938236,1
56,38.01,3.00,Male,Yes,Sat,Dinner,4,7.892660,1
59,48.27,6.73,Male,No,Sat,Dinner,4,13.942407,1
83,32.68,5.00,Male,Yes,Thur,Lunch,2,15.299878,1
85,34.83,5.17,Female,No,Thur,Lunch,4,14.843526,1


In [52]:
df2[df2['tip_percentage']>20]

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,high_spender
6,8.77,2.00,Male,No,Sun,Dinner,2,22.805017,0
9,14.78,3.23,Male,No,Sun,Dinner,2,21.853857,0
14,14.83,3.02,Female,No,Sun,Dinner,2,20.364127,0
17,16.29,3.71,Male,No,Sun,Dinner,3,22.774708,0
18,16.97,3.50,Female,No,Sun,Dinner,3,20.624632,0
20,17.92,4.08,Male,No,Sat,Dinner,2,22.767857,0
42,13.94,3.06,Male,No,Sun,Dinner,2,21.951220,0
46,22.23,5.00,Male,No,Sun,Dinner,2,22.492128,1
51,10.29,2.60,Female,No,Sun,Dinner,2,25.267250,0
63,18.29,3.76,Male,Yes,Sat,Dinner,4,20.557682,0


In [53]:
df2.groupby('sex')['tip'].mean()

/tmp/ipython-input-2624254448.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2.groupby('sex')['tip'].mean()


,tip
sex,
Male,3.089618
Female,2.833448


In [54]:
df2.groupby('sex')['tip'].mean()

/tmp/ipython-input-2624254448.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2.groupby('sex')['tip'].mean()


,tip
sex,
Male,3.089618
Female,2.833448


In [55]:
df2.groupby('smoker')['tip_percentage'].mean()

/tmp/ipython-input-592247845.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2.groupby('smoker')['tip_percentage'].mean()


,tip_percentage
smoker,
Yes,16.319604
No,15.932846


In [56]:
df2.groupby('day')['total_bill'].mean()

/tmp/ipython-input-577940514.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2.groupby('day')['total_bill'].mean()


,total_bill
day,
Thur,17.682742
Fri,17.151579
Sat,20.441379
Sun,21.410000


In [57]:
df2.corr(numeric_only=True)

,total_bill,tip,size,tip_percentage,high_spender
total_bill,1.000000,0.675734,0.598315,-0.338624,0.787342
tip,0.675734,1.000000,0.489299,0.342370,0.554292
size,0.598315,0.489299,1.000000,-0.142860,0.497736
tip_percentage,-0.338624,0.342370,-0.142860,1.000000,-0.250158
high_spender,0.787342,0.554292,0.497736,-0.250158,1.000000


In [65]:
arr1=np.arange(1,17).reshape(4,4)

In [66]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
arr=np.array([1,5,6,8,7,2,])

In [72]:
arr

array([1, 5, 6, 8, 7, 2])

In [73]:
arr[arr%2==0]=-1    #To replace all even numbers as -1

In [74]:
arr

array([ 1,  5, -1, -1,  7, -1])

In [75]:
arr2=np.array([10,20,30,40,50])

In [76]:
arr3=np.mean(arr2)

In [77]:
arr3

np.float64(30.0)

In [78]:
arr4=np.std(arr1)

In [79]:
arr4

np.float64(4.6097722286464435)

In [81]:
normalized=(arr2-np.mean(arr2))/np.std(arr2)    #To find normilized form of the array

In [82]:
normalized

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [83]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9,]
])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a[0][1]

np.int64(2)

In [86]:
a[1][1]

np.int64(5)

In [87]:
a[2][0]

np.int64(7)

In [88]:
a[2]

array([7, 8, 9])

In [96]:
a[2:]

array([[7, 8, 9]])

In [98]:
a[1:,:2]

array([[4, 5],
       [7, 8]])

In [102]:
a[:2,1:]

array([[2, 3],
       [5, 6]])